[[index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[[index]]
name = 'aliyun'
url = "https://mirrors.aliyun.com/pypi/simple/"

[[index]]
name = 'tencent'
url = "http://mirrors.cloud.tencent.com/pypi/simple"

[[index]]
name = 'tsinghua'
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[[index]]
name = 'douban'
url = "http://pypi.douban.com/simple"

[[index]]
name = 'ustc'
url = "https://pypi.mirrors.ustc.edu.cn/simple/"

[[index]]
name = "pypi"
url = "https://pypi.org/simple"
